[build]
  publish = "dist/"
  command = "yarn build"

[[headers]]
  for = "/*"

  [headers.values]
    Strict-Transport-Security = "max-age=15552000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy-Report-Only = '''default-src 'self';
    script-src 'self' https://www.google-analytics.com;
    img-src 'self' https://www.google-analytics.com;
    connect-src 'self' https://www.google-analytics.com;
    frame-ancestors 'none';
    worker-src 'self';
    block-all-mixed-content;
    disown-opener;'''
