[build]
  publish = "dist/"
  command = "yarn build"

[[headers]]
  for = "/*"

  [headers.values]
    Strict-Transport-Security = "max-age=15552000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
